### ISSUE TITLE
[Estrutura] Definição de Paleta de Cores

### ISSUE THREAD

**Issue by mikelfcosta** [mikelfcosta/slackers#2]
Necessário definir as cores que serão utilizadas na Revista Digital.

**Comment by Alexpodoliako** [comment]
![color-palettes](https://cloud.githubusercontent.com/assets/26700195/24338073/e5e8e212-1278-11e7-832c-5e297416ef39.jpg)

**Comment by mikelfcosta** [comment]
Curti mais a paleta (6). Acredito que o contraste do cinza escuro com o cinza claro será melhor, e até combina com o meu Linux.
![screenshot from 2017-03-27 23-37-57](https://cloud.githubusercontent.com/assets/8500559/24386520/6ef12e70-1346-11e7-9e22-d5ad02bb11bb.png)
